spring:
  application:
    name: microservice-api-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    rabbitmq:
      queue: zipkin

server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

#zuul:
#  ignored-services: microservice-provider-user                        # 需要忽视的服务(配置后将不会被路由)
#  routes:
#    movie:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
#      path: /movie/**                                                 # 想要映射到的路径
#      service-customerId: microservice-consumer-movie-ribbon-with-hystrix     # Eureka中的serviceId
