eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    eureka-server-read-timeout-seconds: 8
    eureka-server-connect-timeout-seconds: 500

server:
  port: 8750
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: scaffold-route-operate
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:
    cache: false
    content-type: text/html
    check-template-location: true
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path: classpath:/templates/


feign:
  hystrix:
    enabled: false

logging:
  config: classpath:logback-spring.xml
  path: /scaffold/log
  file: ${spring.application.name:scaffold-route-operate}
tx-lcn:
  client:
    manager-address: 127.0.0.1:8890
