version: "3.7"

services:
  micro-sys:
    entrypoint: ./wait-for-it.sh tx_manager:7970 'java -jar scaffold-business-sys-service-1.0-SNAPSHOT.jar'
    image: scaffold-cloud/scaffold-business-sys-service:1.0-SNAPSHOT
    volumes:
      - /tmp:/tmp
      - ./.scripts/wait-for-it.sh:/wait-for-it.sh
    ports:
      - 8750:8750
    networks:
      - scaffold-cloud
    depends_on:
      - redis
      - eureka
      - mysql
      - rmqbroker
      - rmqnamesrv
      - tx_manager
  route-operate:
    entrypoint: ./wait-for-it.sh micro-sys:8750 'java -jar scaffold-route-operate-1.0-SNAPSHOT.jar'
    image: scaffold-cloud/scaffold-route-operate:1.0-SNAPSHOT
    volumes:
      - /tmp:/tmp
      - ./.scripts/wait-for-it.sh:/wait-for-it.sh
    ports:
      - 8850:8850
    networks:
      - scaffold-cloud
    depends_on:
      - micro-sys
  eureka:
    entrypoint: java -jar scaffold-eureka-1.0-SNAPSHOT.jar
    image: scaffold-cloud/scaffold-eureka:1.0-SNAPSHOT
    volumes:
      - /tmp:/tmp
    ports:
      - 8761:8761
    networks:
      - scaffold-cloud
  zuul:
    entrypoint: ./wait-for-it.sh eureka:8761 'java -jar scaffold-zuul-1.0-SNAPSHOT.jar'
    image: scaffold-cloud/scaffold-zuul:1.0-SNAPSHOT
    volumes:
      - /tmp:/tmp
      - ./.scripts/wait-for-it.sh:/wait-for-it.sh
    ports:
      - 8861:8861
    networks:
      - scaffold-cloud
    depends_on:
      - eureka
  tx_manager:
    entrypoint: ./wait-for-it.sh mysql:3306,redis:6379 'java -jar scaffold-txmanager-1.0-SNAPSHOT.jar'
    image: scaffold-cloud/scaffold-txmanager:1.0-SNAPSHOT
    volumes:
      - /tmp:/tmp
      - ./.scripts/wait-for-it.sh:/wait-for-it.sh
    ports:
      - 8890:8890
      - 7970:7970
    networks:
      - scaffold-cloud
    depends_on:
      - mysql
      - redis
      - eureka
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    restart: always
    networks:
      - scaffold-cloud
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass pwd8ok8
    networks:
      - scaffold-cloud
  rmqnamesrv:
    image: foxiswho/rocketmq:server-4.5.2
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rmq/logs:/opt/logs
      - ./rmq/store:/opt/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms128m -Xmx128m -Xmn128m"
    networks:
      - scaffold-cloud
  rmqbroker:
    image: foxiswho/rocketmq:broker-4.5.2
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rmq/logs:/opt/logs
      - ./rmq/store:/opt/store
      - ./rmq/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms128m -Xmx128m -Xmn128m"
    command: ["/bin/bash","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv
    networks:
      - scaffold-cloud

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8180:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      - scaffold-cloud
networks:
  scaffold-cloud:
    name: scaffold-cloud
    driver: bridge