server:
  port: 8861

spring:
  application:
    name: scaffold-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
logging:
  config: classpath:logback-spring.xml
