server:
  port: 8871
spring:
  application:
    name: scaffold-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fatezhang/scaffold-config.git
          username: Fatezhang
          password: zhangjiaheng521